#!/bin/bash

# Save current user directory location in order to go back there after
# this action
DIR_BEFORE_ACTION=$PWD

cd ${PILSBOT_ROOT_DIR}

colcon build --symlink-install $1

# source the environment again because install/setup.bash exists (what is not
# always the case after a 'pilsbot clean' or when building for the first time)
source env.sh

# Go back to the directory where the user was in before this action.
cd $DIR_BEFORE_ACTION
