#!/bin/bash

if [[ -z "$1" ]]; then
  echo "options:"
  echo "    pilsbot build"
  echo "    pilsbot clean"
  echo "    pilsbot help"
  echo "    pilsbot init"
  echo "    pilsbot launch <your_launch_file.launch>"
  echo "        e.g. pilsbot launch pilsbot_simulation pilsbot.launch.py"
  echo "    pilsbot update"
fi
