#!/bin/bash

# Install ros2 and the tools needed to update and build the pilsbot workspace

# Install git and colcon
sudo apt install -y git python3-colcon-common-extensions

# Install ROS 2 (bash code taken from install page from ROS2 with debian packages)

locale
sudo apt update && sudo apt install locales
sudo locale-gen en_US en_US.UTF-8
sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
export LANG=en_US.UTF-8
locale

# Add the ROS 2 apt repositories
sudo apt update && sudo apt install -y curl gnupg2 lsb-release
curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
sudo sh -c 'echo "deb [arch=$(dpkg --print-architecture)] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2-latest.list'

sudo apt update
sudo apt install -y ros-foxy-desktop
sudo apt install -y ros-foxy-ros-base

source /opt/ros/foxy/setup.bash

# ROS 2 autocomplete
sudo apt install -y python3-pip
pip3 install -U argcomplete

# Install VCSTools
sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
sudo apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv-key 0xAB17C654
sudo apt-get update
sudo apt-get install python3-vcstool

# install nvm and nodejs
npm i rclnodejs
npm i ws
sudo apt install -y ros-foxy-gazebo-ros-pkgs ros-foxy-joint-state-publisher ros-foxy-xacro ros-foxy-diff-drive-controller

# the installation, then update the project workspace
pilsbot update
