#!/bin/bash

# TODO: install dependencies, install ros2 and vcs here to simplify


# For ubuntu 20.04 and ros2 foxy
# install nvm and nodejs
npm i rclnodejs
npm i ws
sudo apt install ros-foxy-gazebo-ros-pkgs ros-foxy-joint-state-publisher ros-foxy-xacro

# the installation, then update the project workspace
pilsbot update


